import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(("localhost", 5000))
print(s.getsockname())
s.listen(5)
client_socket, client_adress = s.accept()
print("Message recu")
print(client_socket)
print(client_adress)
data = client_socket.recv(1024)
print(data.decode("utf-8"))
client_socket.sendall("Bien recu".encode("utf-8"))
client_socket.close()
s.close()
